### ISSUE TITLE
Bug : 레시피 작성 페이지 이슈 목록

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-fe#106]
### 한 일

@dusunax 

1. 레시피 작성 완료 버튼을 ***여러번 클릭*** 하면, 해당 레시피가 여러번 작성 됩니다.
   아마도, API 호출이 여러번 되는 것 같네요.

2. 레시피 작성 완료 후에 페이지가 ***레시피 상세보기*** 로 넘어갑니다.
   그 상태에서 ***뒤로가기 아이콘*** 을 클릭 시, 레시피 작성 페이지로 갑니다.
   해당 부분이 전체 조회로 가야하지 않을까요?

### 환경 설정

```cmd
OS:
Node: 16.15.1(unchpatered) 16.16.0(sumin-dev, subeom-lee)
npm : 8.1.1(all)
```

**Comment by dusunax** [comment]
- 재료 저장 광클하면 여러개 생성
- 재료 선택할 때 뒤로가기 버튼 => 재료 이름까지만 넘어가야 함
- 재료 삭제한 다음 상태에서 뒤로가기 막아야함

**Comment by dusunax** [comment]
### 5. 지금 재료 완성 버그 있음: 9월 22일 8시
### 6. 재료를 삭제한 경우 빼고 / 재료 수정을 위해 `뒤로 가기` 다시 활성화
### 7. SVG 아이콘 삐딱하게 돌아감
