### ISSUE TITLE
Update : resizedUrl & imageUrl

### ISSUE THREAD

**Issue by dusunax** [cupicks/cupicks-fe#111]
### resizedUrl & imageUrl

백엔드 이슈, 9월 16일 밤~17일 새벽 동안 resizedUrl 에러나던 부분 수정되었습니다.

### 그래서!

프로필 이미지, 댓글 이미지 등록 후 사용하실 때 onError를 이용해서
resizedUrl & imageUrl를 적용해주시면 될 것 같습니다.

(프로필 이미지와 댓글 이미지 모두 리사이징에 약 10초 소요)

## => onError 적용이 전부 완료되면 Close할 예정입니다!

**Comment by cmun2** [comment]
# 적용방법 1
![image](https://user-images.githubusercontent.com/66786557/191020710-a1a5ded7-140b-4a72-9ce5-254ec9e61f64.png)
![image](https://user-images.githubusercontent.com/66786557/191020780-6d59383f-b3c0-4e59-94c7-5236ef94eb51.png)

![image](https://user-images.githubusercontent.com/66786557/191024677-7caaa25c-806b-465f-a17d-ddb8c52ef32f.png)
사진이 깜빡임 현상이 일어나며 src로 입력받을때 undefined로 resizedUrl이 해석되는 부분을 알 수 있습니다.
이부분이 해결방법이 필요해보입니다.

특이사항 : 새로고침할때는 이미지가 다시 정상적으로 로드 됩니다.

**Comment by cmun2** [comment]
이미지 resizing이 될때 몇초간의 시간이 필요하여 로딩이 될때 undefined로 출력이 되는것으로 보입니다. 
그리하여 처음에 
![image](https://user-images.githubusercontent.com/66786557/191147012-d7f16907-5551-4be8-8af9-bb2c85769d20.png)
방식으로 image가 resize의 시간을 가지는시간이 몇초간의 시간이 필요하니 로딩 자체를 그 이후에 하면 좋을것같다 생각하여 실행했지만 큰 결함이 세가지 있었습니다.
* accesstoken 시간만료
* 3초간의 불필요한 waiting 시간
* setTimeout에 의존

이를 해결하고자 onError의 속성을 우선 undefined로 resizedUrl이 보여지는 시간때 onError로 comment.imageUrl을 보여주고
사용자가 업로드 이후 다시 get을 가져올때는 계속 resizedUrl으로 출력되도록 하게 만들었습니다.
하지만 imageUrl을 그대로 출력할시 원본이미지의 pixel 그대로 가져오기 때문에 그 시간에는 css로 max-width와 max-height을
잡고 유저에게는 그 순간에는 imageUrl의 max-width와 max-height이 적용된 이미지 파일을 보여주고 이후 다시 get을 가져올때는 resizedUrl으로 가져오며 server에 get할때 용량을 부담을 줄이는 방법을 적용하며 원하던대로 로직이 작동하였습니다.

![image](https://user-images.githubusercontent.com/66786557/191146913-0a1bdb5e-61d3-4757-8e56-73e4dbaa620d.png)
![image](https://user-images.githubusercontent.com/66786557/191147610-49196f54-39f8-49e0-b2e8-e11227e653e4.png)
