### ISSUE TITLE
Bug : 회원가입단계에 관련된 에러 모음

### ISSUE THREAD

**Issue by wonseok-do** [cupicks/cupicks-fe#55]
## 회원 가입 페이지

회원가입 페이지 내
진행 단계에 관련된 에러 모음

### 1. 기존 로직: 이메일 인증을 완료하면 `입력 input`과 `인증 요청 버튼`을 disable 시켰습니다.
  - 문제점:
    - 다음 단계에서 뒤로 가기 버튼을 누르면 막은 input과 버튼이 활성화되고, 
       다른 이메일을 입력할 수 있게 됩니다.(하면 안됨)
  - 해결 방안:
    - 유저가 전 단계로 이동해서 이메일을 수정할 필요성이 없기 때문에
      이전 단계(이메일 인증 단계)로 이동하게 될 경우,
      유저에게 "처음부터 진행해야 함"을 알린 후,
      처음부터 인증을 진행하도록 수정하려고 합니다.
    - 관련 UI 요청 후 작업물 받음

### 2. 기존 로직: 닉네임 인증을 완료하면 `가입하기 버튼`을 누를 수 있습니다.
  - 문제점:
    - 다음 단계에서 뒤로 가기 버튼을 눌렀다가 돌아왔을 시,
       인풋창이 비어있거나, 다른 닉네임이 input에 있어도
       가입하기 버튼을 누를 수 있습니다.(되면 안됨)
  - 해결 방안:
    - 이메일 인증 방식과 동일하게, 뒤로 가기 버튼을 누를 시에
       "처음부터 가입 단계를 다시 해야함"을 알리고
       회원가입 첫 단계로 이동하도록 수정하려고 합니다. 

### 3. 기존 로직: 닉네임 인증을 완료하면 `가입하기 버튼`을 누를 수 있습니다.
  - 문제점:
    - 닉네임 인증을 완료한 후, 가입하기 버튼이 활성화되는데,
       이후 닉네임을 수정할 경우 가입하기 버튼이 비활성화 되어야 합니다.
       왜냐면 지금은 인증한 닉네임이 아니라, 다른 닉네임으로도 가입할 수 있기 때문입니다.
      따라서 닉네임을 수정할 경우, 닉네임 중복 확인(인증)을 다시 진행해야 합니다.
  - 해결방안 A : 리셋버튼 만들기
    - 닉네임 인증을 완료했을 때 => nicknameVerifyToken이 존재
      닉네임 인풋 disabled / 닉네임 인증하기 버튼 => 리셋 버튼으로 바뀜
    - 리셋 버튼을 눌렀을 때! disable 풀고 인풋 비우고 token지우기  
   - 해결방안 B : onChange로 감시
      input창에서 onChange 이벤트가 발생했을 때, nicknameVerifyToken이 존재하면
      token을 지우고, 인증을 다시 진행

### 4. 마지막 단계에서 완료 버튼을 누를 때만 submit이 일어나야 합니다.
  - token또는 단계별 state 조건으로 처리했을 때,
    마지막 단계에서 닉네임 인증 버튼을 눌렀을 때
 
### 해결 방법

1번, 2번, 3번 해결 방법
  - 뒤로가기를 누를 시, 처음 단계부터 진행하도록 하는 해결 방안
  - UI 모달창 추가
![image](https://user-images.githubusercontent.com/94776135/189473234-97fd0371-10f5-4ddc-8079-2f58ab0b1d02.png)

4번 해결 방법
  - 닉네임 인증 단계와 프로필 사진 입력 단계를 서로 바꿔서,
    기존 조건(token이 있고, 마지막 단계일 때 submit)에도 정상적으로 작동하도록 하였음

  
---

- 기록

```
이메일
이미 중복된 이메일이나 사용할 수 없는 이메일 경우
1.이메일 인증번호 발송 버튼 누른 후 -> 알림창 띄움 -> 버튼 disabled
- 이메일을 그대로 남긴다
- 이메일을 리셋시킨다
4.이메일 인증번호 발송 버튼 누른 후 -> 알림창 띄움 -> error메시지 띄움


인증번호
인증번호 확인 후 버튼 막기?
인증번호 확인 후 토큰 받고 인증번호 다시 수정하면 계속하기 버튼 눌러짐
인증번호 못건드리게 막아야 하나?

이메일, 인증번호 인증하고 이메일 인증번호를 바꾼 상태로 계속하기 됨
문제가 생겨서 이메일 인증하고 회원가입을 완료하지 못할경우
다시 회원가입할 때 이메일 토큰이 있어서 그 이메일 재사용안됨

이메일 다음으로 넘어가기 전에 이메일하고 인증번호가 수정안되게 해야 하나?
아니면 계속하기 버튼을 누를 때 기존의 이메일하고 인증번호를 수정하면 계속하기 버튼을 누르지 못하게 해야하나?

계속하기  -> 뒤로가기했을 때 바로 전 페이지로 뒤로가기 해야하나
뒤로가기 눌렀을 때 회원가입을 처음부터 다시 해야하나

이메일하고 인증번호을 인증하고 input에 disabled를 걸어 유저가 다시 작성하지 못하게 함

이메일, 인증번호를 인증하고 새로고침을 누르면 토큰이 사라져야하나
다시 처음부터 작성하게끔 유도?

잘못된 인증번호를 입력했을 때 못누르게? 어떻게?

닉네임 에러발생
중복확인 후 -> 뒤로가기 버튼 누르고 계속하기 누르면 -> 회원가입 완료됨
```

**Comment by wonseok-do** [comment]
### 이메일과 닉네임 인증 토큰 리셋 이슈
회원가입을 하다가 중간에 취소했을 때 이메일 인증을 했을 경우 이메일 인증 토큰이 남아있어 회원가입을 완료하지 못했음에도 불구하고 다음에 그 이메일을 사용하지 못합니다 -> 취소했을 때 이메일 인증 토큰 리셋하는 방법을 사용해봅니다
+ React-hook-form에 있는 useForm() -> reset, resetField 함수 사용
```
const before = () => {
    if (level === 0) {
      navigate("/signIn");
    } else {
      // const emailToken = getValues("emailVerifyToken");
      // reset("emailVerifyToken");
      // reset("Number");
      // reset(getValues("email"));
      reset({ emailVerifyToken: undefined });
      // setValue("emailVerifyToken", undefined);
      // resetField("emailVerifyToken");
      // console.log(getValues("emailVerifyToken"));
      setLevel(0);

      // resetField(getValues("emailVerifyToken"));
      // console.log(getValues("emailVerifyToken"));
    }
  };
```
중간에 setValue와 getValues를 사용해봤지만 콘솔에는 undefined 값을 만들어도 서버자체에서 token 값이 남아있어 불가능합니다 -> 백엔드분들과 의견을 조율해봐야 합니다
닉네임도 비슷한 방법으로 해봐야 할 것 같습니다.

**Comment by dusunax** [comment]
### BE 이슈 등록했습니다.
- Reqeust : 이메일 & 닉네임 인증 취소
https://github.com/cupicks/cupicks-be/issues/115
