### ISSUE TITLE
Bug :  `커뮤니티탭` 에서 새로고침 시 에러 발생

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-fe#80]
@dusunax  @wonseok-do  @cmun2 

### 한 일

갤럭시 S10 5G 기준으로 ***https://cupick.co/*** 로 접속을 했습니다.
해당 페이지로 들어가면 바로 ***https://cucpick.co/recipe*** 로 리다이렉트 됩니다.

해당 페이지에서 사용을 하다가 ****새로고침*** 을 하면 버그가 발생합니다.

### 에러 내용

새로고침하면 다음과 같이 에러 페이지가 나옵니다 :)

![image](https://user-images.githubusercontent.com/86306802/190367418-fc5584cb-97d6-4148-a035-22480439f8de.png)

### 환경 설정

```cmd
OS: Galaxy S10 5G
Node: 16.15.1(unchpatered) 16.16.0(sumin-dev, subeom-lee)
npm : 8.1.1(all)
```

**Comment by dusunax** [comment]
## 에러 페이지 수정하기
