### ISSUE TITLE
Bug : 모달 창을 제외한 곳을 클릭했을 때 다시 작동하지 않는 에러 발생

### ISSUE THREAD

**Issue by wonseok-do** [cupicks/cupicks-fe#82]
### 한 일

모달 창을 제외한 곳을 클릭했을 때 다시 작동하지 않는 에러 발생

### 에러 내용
<를 눌렀을 때 모달 창이 뜸
![모달 창 에러1](https://user-images.githubusercontent.com/108975442/190417183-a4482ab6-72c8-485f-a084-7fcc5f6876a2.png)
모달 창을 제외한 곳을 클릭 후
![모달 창 에러2](https://user-images.githubusercontent.com/108975442/190417466-359eae30-7650-462a-8d39-3d7bbf47d549.png)
<를 눌렀을 때 모달 창이 뜨지 않는 에러 발생

**Comment by dusunax** [comment]
## 수정 완료!👍

### 배경 클릭 시, onDeined로 보내는 setState 함수를 실행해야할 필요가 있습니다.
- 매개변수로 받은 함수를 onClick내 다른 코드들과 같이 실행할 수 없어 onMouseDown을 사용하였습니다.
- 이벤트를 두 번 읽는 것이 좋지 않다고 생각됩니다. 추후 다른 좋은 방법이 있다면 교체할 예정입니다.
```jsx
<StModal
  backgroundColor={backgroundColor}
  timer={timer * 0.001}
  **onMouseDown={onDenied}**
  onClick={()=>{
    modalContents.current.className='contents fade_out'
    setTimeout(()=>{
      setModalShow(false)
    }, 1000)
  }}
>
```
### 버튼에 curser: pointer 적용하였습니다.
- 모바일 웹이더라도, 데스크톱에서 접속할 확률이 있기 때문에 링크, 버튼 등에는 cursor: pointer를 사용하는 것이 좋다고 생각됩니다.
