### ISSUE TITLE
Bug : 무한스크롤 setTimeout 뷰 문제

### ISSUE THREAD

**Issue by dusunax** [cupicks/cupicks-fe#90]
### 무한스크롤 setTimeout 뷰 문제

- 문제점

1. threshold, 스크롤이 내려가는 속도, setTimeout의 값이 서로 맞지 않습니다. 게시물을 로딩하는 서버의 성능이 떨어지는 것 같이 보이기 때문에 먼저 수정해놓습니다. 필요하다면 다르게 바꿔주시면 됩니다.

- 기존
  - src\components\recipeMain\AllRecipeList.jsx 
```jsx
// 18번째 줄  
const [ref, inView] = useInView({
  threshold: 0.8,
});
...
// 65번째 줄
useEffect(() => {
  if (inView && !loading) {
    setTimeout(() => {
      setPage(page + 1);
    }, 1500);
    // page.current += 1;
  }
}, [inView, loading]);
```

- 수정
```jsx
useEffect(() => {
  if (inView && !loading) {
    setPage(page + 1);
  }
}, [inView, loading]);
```

2. 첫번째 무한 스크롤이 내려갈 때 요청이 여러번 되는 것 같습니다. CSS 작업 중 생긴 문제인지, 로딩에 문제가 있는건 지 같이 확인해보아야 할 것 같습니다.

3. 아이템이 100vh보다 적을 때 무한 스크롤이 무한 반복이 됩니다.

**Comment by cmun2** [comment]
# 원인
✔  inView가 바닥을 닿을때 끊없이 page + 1이 일어나기에 끝없는 렌더링이 일어남
* item을 한번에 받아오는 count를 세는 state을 만들어 총 받아오는 아이템의 길이가 일정하게 6개씩의 데이터를 받아오는 길이보다 크거나 같을때만 page가 1씩 늘어나도록 조건을 달아 해결하였습니다.
 
```
const [counting, setCounting] = useState(0);

useEffect(() => {
    //마지막 요소를 보고 로딩중이 아니라면
    if (inView && !loading && items.length >= counting) {
      setTimeout(() => {
        setPage(page + 1);
        setCounting(counting + 6);
      }, 1500);
    }
  }, [inView, loading]);
```
